Update api.yml

diff --git a/.github/workflows/api.yml b/.github/workflows/api.yml
--- a/.github/workflows/api.yml
+++ b/.github/workflows/api.yml
@@ -1,18 +1,64 @@
-name: Process JSON Input
+name: Postman Newman API Tests
 
 on:
-  push:
-  workflow_dispatch:
+  workflow_call:
     inputs:
-      jsonInput:
-        description: "JSON object input"
-        required: true
-        default: '{"key1":"value1","key2":"value2"}'
+      postman_collection_location:
+        type: string
+        default: ./api.postman_collection.json
+      postman_env_content:
+        type: string
+        default: '{"id":"env","values":[{"baseUrl":"localHost"}]}'
 
 jobs:
-  process-json:
+  newman-tests:
     runs-on: ubuntu-latest
+
     steps:
-      - name: Print JSON Input
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      - name: Debug env_content input
         run: |
-          echo "Received JSON: ${{ inputs.jsonInput }}"
+          echo "env_content: '${{ inputs.postman_env_content }}'"
+        
+      - name: Check if collection file exists
+        id: check_file
+        run: |
+          if [ ! -f ./api.postman_collection.json ]; then
+            echo "Collection file not found!"
+            exit 1  # Fail the job if the file doesn't exist
+          fi
+      - name: prepare env file
+        if: steps.check_file.outcome == 'success'
+        run: |
+          echo "Environment file content:"
+          echo "${{ github.event.inputs.env_content }}" > postman_env.json
+          cat postman_env.json
+          
+      - name: Validate JSON structure
+        run: cat postman_env.json | jq .
+
+      - name: Set up Node.js
+        if: steps.check_file.outcome == 'success'
+        uses: actions/setup-node@v3
+
+      - name: Install dependencies
+        if: steps.check_file.outcome == 'success'
+        run: |
+          npm install -g newman newman-reporter-ctrf-json
+          
+      - name: Debug env file
+        run: cat postman_env.json
+
+      - name: Run Newman tests
+        if: steps.check_file.outcome == 'success'        
+        run: |
+          newman run ./api.postman_collection.json \
+            --environment postman_env.json \
+            -r cli,ctrf-json \
+            --reporter-ctrf-json-test-type api \
+            --reporter-ctrf-json-app-name 'Api Testing result'
+      - name: Export test summary
+        if: steps.check_file.outcome == 'success'
+        run: npx github-actions-ctrf ./ctrf/ctrf-report.json
