test run without postman collection

diff --git a/.github/workflows/api.yml b/.github/workflows/api.yml
--- a/.github/workflows/api.yml
+++ b/.github/workflows/api.yml
@@ -25,7 +25,7 @@ jobs:
         run: |
           if [ ! -f ${{ inputs.postman_collection_location }} ]; then
             echo "Collection file not found!"
-            exit 1  # Fail the job if the file doesn't exist
+            exit 1
           fi
 
       - name: Create env file
@@ -34,14 +34,14 @@ jobs:
           if [ -z "${{ secrets.postman_env_content }}" ]; then
             echo '{"values":[{"baseUrl":"localHost"}]}' > env.json
           else
-            echo "${{ secrets.postman_env_content }}" > env.json
+            echo '${{ secrets.postman_env_content }}' > env.json
           fi
 
       - name: Validate env.json format
         if: steps.check_file.outcome == 'success'
         run: |
           if ! jq empty env.json; then
-            echo "Invalid JSON format in env.json"
+            echo "Invalid JSON format in secrets.postman_env_content"
             exit 1
           fi
 
