Update api.yml

diff --git a/.github/workflows/api.yml b/.github/workflows/api.yml
--- a/.github/workflows/api.yml
+++ b/.github/workflows/api.yml
@@ -37,6 +37,14 @@ jobs:
             echo '${{ secrets.postman_env_content }}' > env.json
           fi
 
+      - name: Validate env.json format
+        if: steps.check_file.outcome == 'success'
+        run: |
+          if ! jq empty env.json; then
+            echo "Invalid JSON format in env.json"
+            exit 1
+          fi
+
       - name: Set up Node.js
         if: steps.check_file.outcome == 'success'
         uses: actions/setup-node@v3
@@ -52,9 +60,10 @@ jobs:
           newman run ${{ inputs.postman_collection_location }} \
             --environment env.json \
             -r cli,ctrf-json \
-            --reporter-ctrf-json-test-type api \
-            --reporter-ctrf-json-app-name 'Api Testing result'
+            --reporter-ctrf-json-test-type api
 
       - name: Export test summary
         if: steps.check_file.outcome == 'success'
-        run: npx github-actions-ctrf ./ctrf/ctrf-report.json
+        run: |
+          npx github-actions-ctrf ./ctrf/ctrf-report.json \
+          --title Api Testing Result
